laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('', ['as' => 'site.index', 'uses' => 'Site\Home\HomeController@getIndex']);

Route::get('painel/auth/login', ['as' => 'painel.login','uses' => 'Painel\Auth\LoginController@getLogin']);
Route::post('painel/auth/login', ['as' => 'painel.auth','uses' => 'Painel\Auth\LoginController@postLogin']);
Route::get('painel/auth/logout', ['as' => 'painel.logout','uses' => 'Painel\Auth\LoginController@getLogout']);
Route::get('a-medilaudo', ['as' => 'site.a-medilaudo.index', 'uses' => 'Site\AMedilaudo\AMedilaudoController@getIndex']);
Route::get('a-medilaudo/estrutura', ['as' => 'site.a-medilaudo.estrutura', 'uses' => 'Site\AMedilaudo\AMedilaudoController@getEstrutura']);
Route::get('a-medilaudo/equipe', ['as' => 'site.a-medilaudo.equipe', 'uses' => 'Site\AMedilaudo\AMedilaudoController@getEquipe']);
Route::get('laudos-e-especialidades', ['as' => 'site.laudos-e-especialidades', 'uses' => 'Site\LaudosEEspecialidades\LaudosEEspecialidadesController@getIndex']);
Route::get('para-hospitais-e-clinicas', ['as' => 'site.para-hospitais-e-clinicas', 'uses' => 'Site\ParaHospitaisEClinicas\ParaHospitaisEClinicasController@getIndex']);
Route::post('para-hospitais-e-clinicas', ['as' => 'site.para-hospitais-e-clinicas.enviar', 'uses' => 'Site\ParaHospitaisEClinicas\ParaHospitaisEClinicasController@postEnviar']);
Route::get('para-medicos', ['as' => 'site.para-medicos', 'uses' => 'Site\ParaMedicos\ParaMedicosController@getIndex']);
Route::post('para-medicos', ['as' => 'site.para-medicos.enviar', 'uses' => 'Site\ParaMedicos\ParaMedicosController@postEnviar']);
Route::get('suporte/{slug_categoria?}', ['as' => 'site.suporte', 'uses' => 'Site\Suporte\SuporteController@getIndex']);
Route::get('suporte/download/{id}', ['as' => 'site.suporte', 'uses' => 'Site\Suporte\SuporteController@getDownload']);
Route::get('noticias', ['as' => 'site.noticias', 'uses' => 'Site\Noticias\NoticiasController@getIndex']);
Route::get('noticias/ler/{slug_noticia}', ['as' => 'site.noticias.detalhes', 'uses' => 'Site\Noticias\NoticiasController@getDetalhes']);
Route::get('faq', ['as' => 'site.faq', 'uses' => 'Site\Faq\FaqController@getIndex']);
Route::get('contato', ['as' => 'site.contato', 'uses' => 'Site\Contato\ContatoController@getIndex']);
Route::post('contato', ['as' => 'site.contato.enviar', 'uses' => 'Site\Contato\ContatoController@postEnviar']);
// NOVAS ROTAS SITE

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Painel',
  'prefix' => 'painel'
], function() {

  Route::get('', ['as' => 'painel.dashboard', 'uses' => function() {
    return view('painel.dashboard.index');
  }]);

  Route::get('download/{arquivo}', function(Illuminate\Http\Request $request){
    $arquivo = $request->arquivo;
    return response()->download(base_path().'/resources/assets/curriculos/'.$arquivo);
  });

  Route::post('gravar-ordem-registros', function(Illuminate\Http\Request $request){
    $itens = $request->input('data');
    $tabela = $request->input('tabela');
    for ($i = 0; $i < count($itens); $i++)
      DB::table($tabela)->where('id', $itens[$i])->update(array('ordem' => $i));
  });

  Route::resource('usuarios', 'Usuarios\UsuariosController', ['as' => 'painel']);

  Route::post('imagens/upload', 'Imagens\ImagensController@postUpload');

  Route::post('toggle-laudo-destaque', function(Illuminate\Http\Request  $request){
		$laudo = Medilaudo\Models\Laudo::find($request->id);
		$laudo->destaque = $request->val;
		$laudo->save();
	});

  Route::post('toggle-noticia-destaque', function(Illuminate\Http\Request  $request){
		$noticia = Medilaudo\Models\Noticia::find($request->id);
		$noticia->is_destaque = $request->val;
		$noticia->save();
	});

  // NOVAS ROTAS DO PAINEL:
  Route::resource('equipe', 'Equipe\EquipeController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
  Route::resource('contato', 'Contato\ContatoController', ['only' => ['index', 'edit', 'update'], 'as' => 'painel']);
  Route::resource('contatos-recebidos', 'Contato\ContatoRecebidoController', ['only' => ['index', 'show', 'destroy'], 'as' => 'painel']);
  Route::resource('faq', 'Faq\FaqController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
  Route::resource('noticias', 'Noticias\NoticiasController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
  Route::resource('suporte_arquivos', 'SuporteArquivos\SuporteArquivosController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
  Route::resource('suporte_categorias', 'SuporteCategorias\SuporteCategoriasController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
  Route::resource('motivos_medicos', 'MotivosMedicos\MotivosMedicosController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
  Route::resource('motivos_hospitais', 'MotivosHospitais\MotivosHospitaisController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
  Route::resource('vantagens', 'Vantagens\VantagensController', ['only' => ['index', 'edit', 'update'], 'as' => 'painel']);
  Route::resource('estrutura_topicos', 'EstruturaTopicos\EstruturaTopicosController', ['only' => ['index', 'edit', 'update'], 'as' => 'painel']);
  Route::resource('estrutura', 'Estrutura\EstruturaController', ['only' => ['index', 'edit', 'update'], 'as' => 'painel']);
  Route::resource('empresa', 'Empresa\EmpresaController', ['only' => ['index', 'edit', 'update'], 'as' => 'painel']);
  Route::resource('especialistas', 'Especialistas\EspecialistasController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
  Route::resource('laudos', 'Laudos\LaudosController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
  Route::resource('bannerextra', 'Bannerextra\BannerextraController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
  Route::resource('chamadas', 'Chamadas\ChamadasController', ['only' => ['index', 'edit', 'update'], 'as' => 'painel']);
  Route::resource('videohome', 'VideoHome\VideoHomeController', ['only' => ['index', 'edit', 'update'], 'as' => 'painel']);

});

laravel/app/Http/Controllers/Painel/Bannerextra/BannerextraController.php
<?php

namespace Medilaudo\Http\Controllers\Painel\Bannerextra;

use Illuminate\Http\Request;
use Medilaudo\Http\Controllers\Controller;

use Medilaudo\Models\BannerExtra;
use Medilaudo\Libs\Thumbs;

class BannerextraController extends Controller
{
    protected $pathImagens = 'bannerextra/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = BannerExtra::ordenado()->get();

      return view('painel.bannerextra.index')->with(compact('registros'));
    }

    public function create(Request $request)
    {
      return view('painel.bannerextra.create');
    }

    public function store(Request $request)
    {
      $this->validate($request, [
        'titulo' => 'required',
        'link' => 'required',
        'data_inicio' => 'required|date_format:d/m/Y',
        'data_termino' => 'required|date_format:d/m/Y'
    	]);

      $object = new BannerExtra;

      $object->titulo = $request->titulo;
      $object->link = $request->link;
      $object->data_inicio = $request->data_inicio;
      $object->data_fim = $request->data_termino;

      $imagem = Thumbs::make($request, 'imagem', 560, null, $this->pathImagens);
      if($imagem){
      	Thumbs::make($request, 'imagem', 200, null, $this->pathImagens.'thumbs/');
      	$object->imagem = $imagem;
      }

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro criado com sucesso.');

        return redirect()->route('painel.bannerextra.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao criar registro! ('.$e->getMessage().')'));

      }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.bannerextra.edit')->with('registro', BannerExtra::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
      	'titulo' => 'required',
        'link' => 'required',
        'data_inicio' => 'required|date_format:d/m/Y',
        'data_termino' => 'required|date_format:d/m/Y'
    	]);

      $object = BannerExtra::find($id);

      $object->titulo = $request->titulo;
      $object->link = $request->link;
      $object->data_inicio = $request->data_inicio;
      $object->data_fim = $request->data_termino;

      $imagem = Thumbs::make($request, 'imagem', 560, null, $this->pathImagens);
      if($imagem){
      	Thumbs::make($request, 'imagem', 200, null, $this->pathImagens.'thumbs/');
      	$object->imagem = $imagem;
      }

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        return redirect()->route('painel.bannerextra.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

    public function destroy(Request $request, $id){
      $object = BannerExtra::find($id);
      $object->delete();

      $request->session()->flash('sucesso', 'Registro removido com sucesso.');

      return redirect()->route('painel.bannerextra.index');
    }

}

laravel/app/Http/Controllers/Painel/Chamadas/ChamadasController.php
<?php

namespace Medilaudo\Http\Controllers\Painel\Chamadas;

use Illuminate\Http\Request;
use Medilaudo\Http\Controllers\Controller;

use Medilaudo\Models\Chamada;
use Medilaudo\Libs\Thumbs;

class ChamadasController extends Controller
{
    protected $pathImagens = 'chamadas/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = Chamada::ordenado()->get();

      return view('painel.chamadas.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.chamadas.edit')->with('registro', Chamada::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
      	'texto' => 'required',
        'link' => 'required'
    	]);

      $object = Chamada::find($id);

      $object->link = $request->link;
      $object->texto = $request->texto;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        return redirect()->route('painel.chamadas.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

}

laravel/app/Http/Controllers/Painel/Contato/ContatoController.php
<?php

namespace Medilaudo\Http\Controllers\Painel\Contato;

use Illuminate\Http\Request;
use Medilaudo\Http\Controllers\Controller;

use Medilaudo\Models\Contato;
use Medilaudo\Libs\Thumbs;

class ContatoController extends Controller
{
    protected $pathImagens = 'contato/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = Contato::all();

      return view('painel.contato.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.contato.edit')->with('registro', Contato::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $object = Contato::find($id);

      $object->telefone = $request->telefone;
      $object->endereco = $request->endereco;
      $object->google_maps = $request->google_maps;
      $object->linkedin = $request->linkedin;
      $object->facebook = $request->facebook;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        return redirect()->route('painel.contato.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

}

laravel/app/Http/Controllers/Painel/Contato/ContatoRecebidoController.php
<?php

namespace Medilaudo\Http\Controllers\Painel\Contato;

use Illuminate\Http\Request;
use Medilaudo\Http\Controllers\Controller;

use Medilaudo\Models\Contato;
use Medilaudo\Libs\Thumbs;

use Medilaudo\Models\ContatoMedico;
use Medilaudo\Models\ContatoClinica;
use Medilaudo\Models\ContatoRecebido;

class ContatoRecebidoController extends Controller
{

  public function index(Request $request)
  {
    $filtro = $request->filtro;

    if($filtro == 'medicos'){

      $registros = ContatoMedico::ordenado()->get();
      $filtro_extenso = 'Médicos';

    }elseif($filtro == 'clinicas'){

      $registros = ContatoClinica::ordenado()->get();
      $filtro_extenso = 'Hospitais e Clínicas';

    }elseif($filtro == 'contatos' || !$filtro){

      $registros = ContatoRecebido::ordenado()->get();
      $filtro_extenso = 'Contatos';
      $filtro = 'contatos';

    }

    return view('painel.contato.recebidos')->with(compact('registros', 'filtro', 'filtro_extenso'));
  }

  public function show(Request $request, $id)
  {
    $filtro = $request->filtro;

    if(!$filtro) return redirect()->back();

    if($filtro == 'medicos'){

      $registro = ContatoMedico::find($id);
      $filtro_extenso = 'Médicos';

    }elseif($filtro == 'clinicas'){

      $registro = ContatoClinica::find($id);
      $filtro_extenso = 'Hospitais e Clínicas';

    }elseif($filtro == 'contatos'){

      $registro = ContatoRecebido::find($id);
      $filtro_extenso = 'Contatos';

    }

    return view('painel.contato.recebidos-detalhes')->with(compact('registro', 'filtro', 'filtro_extenso'));
  }

  public function destroy(Request $request, $id)
  {

    $filtro = $request->filtro;

    if(!$filtro) return redirect()->back();

    if($filtro == 'medicos'){

      $object = ContatoMedico::find($id);

    }elseif($filtro == 'clinicas'){

      $object = ContatoClinica::find($id);

    }elseif($filtro == 'contatos'){

      $object = ContatoRecebido::find($id);

    }
    $object->delete();

    $request->session()->flash('sucesso', 'Registro removido com sucesso.');

    return redirect()->route('painel.contatos-recebidos.index', ['filtro' => $filtro]);
  }

}

laravel/app/Http/Controllers/Painel/Vantagens/VantagensController.php
<?php

namespace Medilaudo\Http\Controllers\Painel\Vantagens;

use Illuminate\Http\Request;
use Medilaudo\Http\Controllers\Controller;

use Medilaudo\Models\Vantagem;
use Medilaudo\Libs\Thumbs;

class VantagensController extends Controller
{
    protected $pathImagens = 'vantagens/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = Vantagem::all();

      return view('painel.vantagens.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.vantagens.edit')->with('registro', Vantagem::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
      	'titulo' => 'required'
    	]);

      $object = Vantagem::find($id);

      $object->titulo = $request->titulo;
      $object->texto = $request->texto;

      try {

        $object->save();

        $request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        return redirect()->route('painel.vantagens.index');

      } catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

}

laravel/resources/views/painel/suporte_arquivos/create.blade.php
@extends('painel.template.index')

@section('conteudo')

    <div class="container-fluid padded-bottom">

    	<div class="row">
    		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

	      	<h2>Cadastrar Arquivo</h2>

	        <hr>

	        @include('painel.partials.mensagens')

		    </div>
		  </div>

      <form action="{{ URL::route('painel.suporte_arquivos.store') }}" method="post" enctype="multipart/form-data">

  			{!! csrf_field() !!}

  			<div class="row">
  				<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

            <div class="form-group">
              <label for="inputCategoria">Categoria</label>
              <select class="form-control" name="categorias_id" required id="inputCategoria">
                <option value=""></option>
                @forelse($categorias as $cat)
                  <option value="{{$cat->id}}" @if(old('categorias_id') == $cat->id) selected @endif >{{$cat->titulo}}</option>
                @empty
                  <option value="">Sem cadastros</option>
                @endforelse
              </select>
            </div>

            <div class="form-group">
  						<label for="inputTitulo">Título</label>
  						<input type="text" name="titulo" class="form-control" id="inputTitulo" value="{{old('titulo')}}" required>
  					</div>

  			    <div class="form-group">
  						<label for="inputDescritivo">Descritivo</label>
  						<textarea name="descritivo" class="form-control textarea-simples" id="inputDescritivo">{{old('descritivo')}}</textarea>
  					</div>

            <div class="form-group">
              <label for="inputArquivo">Arquivo</label>
              <input type="file" class="form-control" id="inputArquivo" name="arquivo" required>
            </div>

            <hr>

  				</div>
  			</div>

			  <button type="submit" title="Cadastrar" class="btn btn-success">Cadastrar</button>

			  <a href="{{ URL::route('painel.suporte_arquivos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

	  	</form>

    </div>

@endsection

laravel/resources/views/painel/suporte_arquivos/edit.blade.php
@extends('painel.template.index')

@section('conteudo')

  <div class="container-fluid padded-bottom">

    <div class="row">
    	<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

		  	<h2>Editar Arquivo</h2>

		    <hr>

		    @include('painel.partials.mensagens')

		  </div>
		</div>

    <form action="{{ URL::route('painel.suporte_arquivos.update', $registro->id) }}" method="post" enctype="multipart/form-data">

			<input type="hidden" name="_method" value="PUT">

			{!! csrf_field() !!}

			<div class="row">
				<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

          <div class="form-group">
            <label for="inputCategoria">Categoria</label>
            <select class="form-control" name="categorias_id" required id="inputCategoria">
              <option value=""></option>
              @forelse($categorias as $cat)
                <option value="{{$cat->id}}" @if($registro->categorias_id == $cat->id) selected @endif >{{$cat->titulo}}</option>
              @empty
                <option value="">Sem cadastros</option>
              @endforelse
            </select>
          </div>

          <div class="form-group">
            <label for="inputTitulo">Título</label>
            <input type="text" name="titulo" class="form-control" id="inputTitulo" value="{{$registro->titulo}}" required>
          </div>

			    <div class="form-group">
						<label for="inputDescritivo">Descritivo</label>
  					<textarea name="descritivo" class="form-control textarea-simples" id="inputDescritivo">{{$registro->descritivo}}</textarea>
					</div>

          <div class="form-group well">
            @if($registro->arquivo)
              <a href="assets/arquivos/{{$registro->arquivo}}" target="_blank" class="btn btn-sm btn-default">Arquivo Atual</a>
              <hr>
            @endif
            <label for="inputArquivo">Arquivo</label>
            <input type="file" class="form-control" id="inputArquivo" name="arquivo">
          </div>

          <hr>

				</div>
			</div>

			<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

			<a href="{{ URL::route('painel.suporte_arquivos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

		</form>

    </div>

@endsection

laravel/resources/views/painel/suporte_arquivos/index.blade.php
@extends('painel.template.index')

@section('conteudo')

  <div class="container-fluid padded-bottom">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <h2>Suporte - Arquivos</h2>

        <hr>

      	@include('painel.partials.mensagens')

        <a href="{{ URL::route('painel.suporte_arquivos.create') }}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar Arquivo</a>

        <hr>

        <div class="btn-group">
          <a href="{{ URL::route('painel.suporte_arquivos.index') }}" class="btn btn-sm @if($categorias_id == '') btn-primary @else btn-default @endif ">Todas as Categorias</a>
          @foreach($categorias as $c)
            <a href="{{ URL::route('painel.suporte_arquivos.index', ['categorias_id' => $c->id ]) }}" class="btn btn-sm @if($categorias_id == $c->id) btn-primary @else btn-default @endif ">{{$c->titulo}}</a>
          @endforeach
        </div>

        <table class="table table-striped table-bordered table-hover table-sortable" data-tabela='suporte_arquivos'>

          <thead>
          	<tr>
              <th>Título</th>
              <th>Descritivo</th>
          		<th><span class="glyphicon glyphicon-cog"></span></th>
          	</tr>
        	</thead>

        	<tbody>
          	@foreach ($registros as $registro)

            	<tr class="tr-row" id="row_{{ $registro->id }}">
                <td>
                  {{$registro->titulo}}
                </td>
            		<td>
                  {{ str_words(strip_tags($registro->descritivo), 15)  }}
                </td>
            		<td class="crud-actions">
              		<a href="{{ URL::route('painel.suporte_arquivos.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

                  <form action="{{ URL::route('painel.suporte_arquivos.destroy', $registro->id) }}" method="post">
                    {!! csrf_field() !!}
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
                  </form>
            		</td>
            	</tr>

          	@endforeach
        	</tbody>

      	</table>

      </div>
    </div>
  </div>

@endsection